version: "3"

services:
    django:
        build: .
        ports:
            - "80:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=pgdb
            - DB_NAME=secretsanta
            - DB_USER=postgres
            - DB_PASS=thisissecurepassword
        depends_on:
            - pgdb
    pgdb:
        image: postgres:latest
        container_name: pgdb
        environment:
            - POSTGRES_DB=secretsanta
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=thisissecurepassword
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
