# Generated by Django 4.1.7 on 2023-04-02 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moderator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
