# Generated by Django 4.1.7 on 2023-04-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_date_created_alter_event_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='core.event')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts_to_buy', to=settings.AUTH_USER_MODEL)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts_to_recive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
