# Generated by Django 4.1.7 on 2023-04-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
