# Generated by Django 4.1.13 on 2023-11-14 06:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.event_image_file_path),
        ),
    ]
